language: php

php:
  - 5.6
  - 7.0

branches:
  only:
    - master
    - /^\d+\.\d+$/

cache:
  directories:
    - vendor/

before_install:
  - composer self-update

install: 
  - cp phpunit.xml.dist phpunit.xml
  - composer install

script:
  - vendor/phpunit/phpunit/phpunit -c phpunit.xml Tests/ 
